fn main() {
    println!("cargo:rerun-if-changed=gkl");
    cc::Build::new()
        .file("gkl/pairhmm/pairhmm_common.cc")
        .file("gkl/smithwaterman/smithwaterman_common.cc")
        .warnings(false)
        .compile("gkl-common");
    cc::Build::new()
        .file("gkl/pairhmm/avx_impl.cc")
        .file("gkl/smithwaterman/avx2_impl.cc")
        .flag("-mavx2")
        .warnings(false)
        .compile("gkl-avx2");
    cc::Build::new()
        .file("gkl/pairhmm/avx512_impl.cc")
        .file("gkl/smithwaterman/avx512_impl.cc")
        .flag("-mavx512f")
        .flag("-mavx512dq")
        .flag("-mavx512vl")
        .flag("-mavx512bw")
        .warnings(false)
        .compile("gkl-avx512");
}
