name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        rust: ['stable', 'nightly']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      run: |
        rustup install ${{matrix.rust}}
        rustup default ${{matrix.rust}}
    - run: cargo test --verbose
    - run: cargo test --verbose --release
    - run: cargo test --verbose --features c
    - run: cargo test --verbose --features nightly
      if: matrix.rust == 'nightly'

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      run: |
        rustup install nightly
        rustup default nightly
        cargo install cargo-criterion
    - run: cargo criterion --no-run
    - run: cargo criterion --no-run --features c
    - run: cargo criterion --no-run --features nightly

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        run: |
          rustup install stable
          rustup default stable
          rustup component add rustfmt
      - run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo doc
