name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        rust: ['stable', 'nightly']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      run: |
        rustup install ${{matrix.rust}}
        rustup default ${{matrix.rust}}
    - name: Test debug
      run: cargo test --verbose
    - name: Test release
      run: cargo test --verbose --release

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust
      run: |
        rustup install stable
        rustup default stable
        cargo install cargo-criterion
    - name: Bench
      run: cargo criterion --no-run

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        run: |
          rustup install stable
          rustup default stable
          rustup component add rustfmt
      - run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo doc
